name: Update README

on:
  push:
  schedule:
    - cron: "0 */1 * * *"

jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.COMMIT_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: README-bot 🤖
          commit_user_email: readme-bot@leovie.de
          commit_author: README-bot 🤖 <readme-bot@leovie.de>